### ISSUE TITLE
Inconsistent treatment of `fill_value` and `missing_value` during `cubewrite`

### ISSUE THREAD

**Issue by blimlim** [ACCESS-NRI/um2nc-standalone#116]
This issue is related to `cubewrite` refactoring work in #99, where we are extracting the missing_value/fill value modifications into a separate function.

The code is not currently consistent in the way it treats the fill value's type. It first sets a fill value depending on the type of the cube's data, and then writes this to the cube's `missing_data` attribute:
https://github.com/ACCESS-NRI/um2nc-standalone/blob/c1a4a54404347ccba925a5c18249049482309caa/umpost/um2netcdf.py#L331-L339

where the `missing_data` attribute is forced to match the cube data's type.

When the `fill_value` is used later as an argument to to the `sman.write` function, the same type conversion is not applied, e.g: 
https://github.com/ACCESS-NRI/um2nc-standalone/blob/c1a4a54404347ccba925a5c18249049482309caa/umpost/um2netcdf.py#L391-L395

This means there can be a mismatch between the `missing_value` and `fill_values` types. E.g. if the `cube.data.dtype` is `np.float32`, then the `missing_value` will have type `float32`, while the `fill_value` supplied to `sman.write` will use the default python `float64` type.

@MartinDix do you know if there are reasons that the type needs to be treated differently in these two places? In terms of turning this part of the code into a separate function and adding unit tests, I think it becomes simpler if we are able  to convert both the `missing_value` and `fill_value` to match the `cube.data.dtype`.

**Comment by MartinDix** [comment]
The types should match. As far as I know they always did with the original script.

Usual 32 bit input
```
        float fld_s00i023(time, lat, lon) ;
                fld_s00i023:_FillValue = 1.e+20f ;
                fld_s00i023:standard_name = "surface_snow_amount" ;
                fld_s00i023:long_name = "SNOW AMOUNT OVER LAND AFT TSTP KG/M2" ;
                fld_s00i023:units = "kg m-2" ;
                fld_s00i023:um_stash_source = "m01s00i023" ;
                fld_s00i023:missing_value = 1.e+20f ;
                fld_s00i023:cell_methods = "time: mean" ;
                fld_s00i023:grid_mapping = "latitude_longitude" 
```

64 bit output from a 64 bit file
```
        double mrsol(time, depth, lat, lon) ;
                mrsol:_FillValue = 1.e+20 ;
                mrsol:standard_name = "mass_content_of_water_in_soil_layer" ;
                mrsol:long_name = "SOIL MOISTURE CONTENT IN A LAYER" ;
                mrsol:units = "kg m-2" ;
                mrsol:um_stash_source = "m01s08i223" ;
                mrsol:missing_value = 1.e+20 ;
                mrsol:cell_methods = "time: mean" ;
                mrsol:grid_mapping = "latitude_longitude" ;
```

**Comment by blimlim** [comment]
Thanks @MartinDix! That makes it simpler, being able to force both `_Fillvalue` and `missing_value` to use the same type as the cube's data.

**Comment by blimlim** [comment]
Possibly the type conversion for the `_FillValue` attribute happens [within the `netCDF4` library itself](https://github.com/Unidata/netcdf4-python/blob/188cc6c03a8eef0add64c544667b14a0a7b3c85d/src/netCDF4/_netCDF4.pyx#L4413), hence why `um2nc` worried only about converting the separate `missing_value` attribute.
