### ISSUE TITLE
Irrelevant `STASHmaster` warning from mule

### ISSUE THREAD

**Issue by blimlim** [ACCESS-NRI/um2nc-standalone#126]
`process` produces the following warning each time it is run on gadi:
```
/g/data/vk83/apps/payu/1.1.5/lib/python3.10/site-packages/mule/stashmaster.py:259: UserWarning: 
Unable to load STASHmaster from version string, path does not exist
Path: $UMDIR/vn7.3/ctldata/STASHmaster/STASHmaster_A
Please check that the value of mule.stashmaster.STASHMASTER_PATH_PATTERN is correct for your site/configuration
  warnings.warn(msg)
```

Which is raised each time this line is run: https://github.com/ACCESS-NRI/um2nc-standalone/blob/33d0dc5ee9830c46f86bbd478fd75698832d34a8/umpost/um2netcdf.py#L468

The warning fills up the stderr when doing several conversions, and can appear alarming/confusing to the user. @MartinDix mentioned that `um2nc`'s use of `mule` doesn't use any `STASHmaster` information (using `stashvar.py` instead to get the variables' information), meaning that this warning is harmless.

Would it be worth filtering out this warning in order to clean up the output?

**Comment by truth-quark** [comment]
Cleaning up the output also helps simplify test output. Throwing out a few thoughts:
* Can `mule.stashmaster.STASHMASTER_PATH_PATTERN` be modified to point at a valid path?
* Perhaps trap `UserWarnings` from the load & ignore `stash` related ones?

**Comment by blimlim** [comment]
I think trapping the `stash` related user warnings sounds like a good idea – I can put together a small PR. I think it would be difficult to point to a "correct"  `STASHmaster` file as different models use different files, although currently it looks like it's trying to load the ESM1.5 one.
