### ISSUE TITLE
Missing metadata for CASA variables

### ISSUE THREAD

**Issue by MartinDix** [ACCESS-NRI/um2nc-standalone#24]
stashvar_cmip6.py doesn't have metadata for the CABLE CASA variables (codes 851 onwards). As a consequence a netCDF file has
`                fld_s03i851:long_name = "UNKNOWN VARIABLE" ;`

Name information is in `atmosphere/prefix.PRESM_A` in the payu config. Not sure about units at the moment.

**Comment by blimlim** [comment]
Closed by [#158](https://github.com/ACCESS-NRI/um2nc-standalone/pull/158)
