### ISSUE TITLE
Handling ancillary files - flag as error

### ISSUE THREAD

**Issue by MartinDix** [ACCESS-NRI/um2nc-standalone#28]
Ancillary files are the same UM fieldsfile format but don't have some of the header information of model output files.

Using `~access/umdir/ancil/atmos/GC5/n96e/orca1/land_sea_mask/etop01/v1/qrparm.mask` fails with the less than useful

`AttributeError: 'NoneType' object has no attribute 'zsea_at_rho'`

Something like
```
    ff = mule.load_umfile(str(infile))
    if isinstance(ff, mule.ancil.AncilFile):
        raise Exception('Ancillary files are not supported')
```

**Comment by truth-quark** [comment]
Closed by #29.
