### ISSUE TITLE
Additional use of `require_heaviside_uv` and `require_heaviside_t` functions

### ISSUE THREAD

**Issue by blimlim** [ACCESS-NRI/um2nc-standalone#40]
I think this carries over from the original version of the code. In the `process` function, there are a couple of conditionals determining whether to apply the masks to a cube:
https://github.com/ACCESS-NRI/um2nc-standalone/blob/055568f9abfc1ef12458d8edd46a079e7121174f/umpost/um2netcdf.py#L419-L420

https://github.com/ACCESS-NRI/um2nc-standalone/blob/055568f9abfc1ef12458d8edd46a079e7121174f/umpost/um2netcdf.py#L427

It looks like the second parts of the conditions are identical to the ones in the `require_heaviside_uv` and `require_heaviside_t` functions:
https://github.com/ACCESS-NRI/um2nc-standalone/blob/055568f9abfc1ef12458d8edd46a079e7121174f/umpost/um2netcdf.py#L561-L563

https://github.com/ACCESS-NRI/um2nc-standalone/blob/055568f9abfc1ef12458d8edd46a079e7121174f/umpost/um2netcdf.py#L571-L573

Should we swap the conditions in `process` to use these functions?

**Comment by truth-quark** [comment]
Cleaning this sort of logic is definitely part of the refactoring work.

**Comment by truth-quark** [comment]
I'd like to clarify masking requirements for some runtime conditions.

One use case is when do masking is True (the default), but the `heaviside_...` cube vars for masking are missing. Is the desired behaviour:
1. Copy the cube data var to the NC file **without** masking.
2. Ignore the cube data var entirely so it's **not** written to the NC
3. Something else?

**Comment by blimlim** [comment]
> One use case is when do masking is True (the default), but the `heaviside_...` cube vars for masking are missing. Is the desired behaviour:
> 
> 1. Copy the cube data var to the NC file **without** masking.
> 2. Ignore the cube data var entirely so it's **not** written to the NC
> 3. Something else?

Just checking that I properly understand what the original and current versions of the code are doing here – are they currently ignoring the cubes that need masking when the `heaviside` cubes are missing?

Once we've confirmed if this is the desired behaviour, I'm wondering whether it would be useful eventually to make the warnings more detailed than what was originally there, e.g. specifying which variables will be skipped:

https://github.com/ACCESS-NRI/um2nc-standalone/blob/92e4c92c26e44662ef1d4a234725abe9246c1bb4/umpost/um2netcdf.py#L589-L591

**Comment by truth-quark** [comment]
> > One use case is when do masking is True (the default), but the `heaviside_...` cube vars for masking are missing. Is the desired behaviour:
> > 
> > 1. Copy the cube data var to the NC file **without** masking.
> > 2. Ignore the cube data var entirely so it's **not** written to the NC
> > 3. Something else?
> 
> Just checking that I properly understand what the original and current versions of the code are doing here – are they currently ignoring the cubes that need masking when the `heaviside` cubes are missing?

I've got the original & this issue #40 NC outputs as a binary match (excluding the custom history attribute).

Currently, the code identifies cubes requiring masking. If the relevant `heaviside_(uv|t)` cube is missing, the workflow ignores any cubes needing masking & they're never written to the NC.


> Once we've confirmed if this is the desired behaviour, I'm wondering whether it would be useful eventually to make the warnings more detailed than what was originally there, e.g. specifying which variables will be skipped:
> 
> https://github.com/ACCESS-NRI/um2nc-standalone/blob/92e4c92c26e44662ef1d4a234725abe9246c1bb4/umpost/um2netcdf.py#L589-L591

This is a good idea, in addition to clarifying the warning that **skipped means completely excluded from NC output**.

**Comment by truth-quark** [comment]
To add some masking filtering/optimisation thoughts from working with the code:

As of mid-July 2024, if a user wants `heaviside_(uv|t)` masking but the relevant heaviside cubes are missing, several vars are excluded from writing. This occurs at the end of the workflow loop, **after** name changes/data processing etc. This is wasteful & it's simpler to filter out non-maskable cubes much earlier.

An initial suggestion is:
* Use [heaviside flags](https://github.com/ACCESS-NRI/um2nc-standalone/blob/40/refactor-masking/umpost/um2netcdf.py#L315-L316) to determine if masking is possible.
* If not possible, filter `cubes` to remove any cube that requires masking ([excluding it from line 339's loop](https://github.com/ACCESS-NRI/um2nc-standalone/blob/40/refactor-masking/umpost/um2netcdf.py#L339))
* Expand `do_mask` definition, creating a _combined_ condition indicating the user wants masking AND heaviside uv/t is present. This should resolve to false if both heaviside uv/t are missing.
* Then refine the logic here: https://github.com/ACCESS-NRI/um2nc-standalone/blob/40/refactor-masking/umpost/um2netcdf.py#L407-L419

**Comment by truth-quark** [comment]
An example implementation is here:
https://github.com/ACCESS-NRI/um2nc-standalone/blob/40/refactor-masking-filtering/umpost/um2netcdf.py

**Comment by truth-quark** [comment]
This is technically also part of #14.
