### ISSUE TITLE
Driver script – improving success/failure reporting

### ISSUE THREAD

**Issue by blimlim** [ACCESS-NRI/um2nc-standalone#47]
The conversion driver script for ESM1.5 currently reports on the files it tries to convert and whether there were any permitted exceptions from within the `convert_fields_file_list` function:

https://github.com/ACCESS-NRI/um2nc-standalone/blob/1c15a92767ef112e449058d61aa3a3c3edce2f13/umpost/conversion_driver_esm1p5.py#L149-L160

This "buried I/O" could be pulled out of this function and dealt with by the higher level calling function. @truth-quark had the idea of modifying `convert_fields_file_list` to return a sequence specifying which conversions were successful, and which encountered allowed errors, so that the higher level `convert_esm1p5_output_dir` function could report them to the user.

**Comment by blimlim** [comment]
@truth-quark I've had ago putting together a prototype version of this in d54fdaf640c96ebdf7f4938d51cb8360f0a1dc16. 

Would you be happy to take a quick look to check whether its along the lines of what you were thinking? I haven't added in any tests yet as it would be good to know whether the general approach should change.

**Comment by truth-quark** [comment]
> @truth-quark I've had ago putting together a prototype version of this in [d54fdaf](https://github.com/ACCESS-NRI/um2nc-standalone/commit/d54fdaf640c96ebdf7f4938d51cb8360f0a1dc16).
> 
> Would you be happy to take a quick look to check whether its along the lines of what you were thinking? I haven't added in any tests yet as it would be good to know whether the general approach should change.

Yep, I'll have a look & then we can decide if we should add a few tasks to this issue or run via a PR process :-)

**Comment by truth-quark** [comment]
My natural inclination is to do something like:
```Python
def convert_fields_file_list(fields_file_paths, nc_write_dir):
    succeeded = []
    failed = []
    
    for fields_file_path in (Path(p) for p in fields_file_paths):  # NB: logic --> tuple comprehension
        nc_write_path = get_nc_write_path(fields_file_path, nc_write_dir)
    
        try:
            um2netcdf4.process(fields_file_path, nc_write_path, ARG_VALS)
            succeeded.append(fields_file_path)  # TODO: should this be `nc_write_path`?
        except Exception as exc:
            # TODO: Refactor once um2nc has specific exceptions
            if exc.args[0] in ALLOWED_UM2NC_EXCEPTION_MESSAGES.values():
                failed.append((fields_file_path, exc))
            else:
                raise
    
    return succeeded, failed
```

Then in the `convert_esm1p5_output_dir()` calling code: 
```Python
...   # some previous code
succeeded, failed = convert_fields_file_list(
    atm_dir_fields_files,
    nc_write_dir
)
report_results(succeeded, failed). # TODO: some kind of handling...
```
This splits up the successes/failures for independent handling. In `report_results()`, this makes it easier to implement reporting logic like:
```Python
... # some code
for s in succeeded:  # nothing happens with an empty list, ditto failed
    print(f"Converted {s}")
for f in failed:
    print(f"ERROR {s}")
 ...
```
Another bonus, the unit tests can focus specifically on testing success/failure conditions:
```Python
# in test/test_conversion_driver.py
def test_convert_fields_file_list_success():
    # do some setup
   success, _ = convert_fields_file_list(args...):
   assert success[0] = ...

def test_convert_fields_file_list_failed():
    # do some setup
    _, failed = convert_fields_file_list(args...):
   assert failed[0] = ...
```
Does that help?

**Comment by blimlim** [comment]
I think that suggestion is great! Definitely makes it cleaner. I've had a go at implementing this and opened up a pr, and any suggestions there would be great!
