### ISSUE TITLE
Clean & optimise masking logic/workflow

### ISSUE THREAD

**Issue by truth-quark** [ACCESS-NRI/um2nc-standalone#50]
Some `heaviside` masking logic in `process()` can be simplified & optimised (this is a subset of #14).

One `um2nc-standalone` feature is using `heaviside_(uv|t)` cubes to mask data in some other cubes. Sometimes, both the `heaviside_(uv|t)` cubes are missing, preventing the masking operation. If masking cannot take place, it is understood that the _unmasked_ cubes are _excluded_ from the NC output.

As of mid-July 2024, masking logic is spread across the `process()` func & is somewhat tricky. This issue outlines some problems.

First, the decision to perform masking is based on flags determined here:

https://github.com/ACCESS-NRI/um2nc-standalone/blob/ab7b131333300854f0c37a3320026b0b53c6d15a/umpost/um2netcdf.py#L315-L323

The `do_mask` flag doesn't include chained logic to check if masking can actually occur:

https://github.com/ACCESS-NRI/um2nc-standalone/blob/ab7b131333300854f0c37a3320026b0b53c6d15a/umpost/um2netcdf.py#L318

Further down the `process()` workflow, the `do_mask` check _below_ assesses if a cube is required or excluded. This is _near the end_ of the workflow loop, **after** data processing steps. Thus, cubes may be modified then discarded (which should be avoided):

https://github.com/ACCESS-NRI/um2nc-standalone/blob/ab7b131333300854f0c37a3320026b0b53c6d15a/umpost/um2netcdf.py#L407-L419

**Solutions:**

It's simpler & more efficient to completely exclude _non-maskable_ cubes from processing, ideally early in the workflow. An initial suggestion is:

* Use [heaviside flags](https://github.com/ACCESS-NRI/um2nc-standalone/blob/40/refactor-masking/umpost/um2netcdf.py#L315-L316) to determine if masking is possible.
* Expand `do_mask` definition, checking if the user wants masking AND `heaviside uv|t` cubes are present. This should resolve to `False` if **both** `heaviside uv|t` cubes are missing.
* Is this possible: simplify `check_pressure_level_masking()` to **only** return `heaviside uv|t` if needed AND the _mask layer is present_? This would combine the `needs_heaviside_uv|t` flag into heaviside existence tests `if heaviside_t: ...`
* Fix the logic for generating the variable skipping warnings
* If masking isn't possible, filter the cubes to remove any requiring masking. This subsequently excludes some cubes from ever reaching this loop: https://github.com/ACCESS-NRI/um2nc-standalone/blob/ab7b131333300854f0c37a3320026b0b53c6d15a/umpost/um2netcdf.py#L339
* Refine the logic & simplify control flow. The `continue` statements _below_ relate to a loop higher in the code. These `continue` statements quietly skip cube writing, so control flow & behaviour is less clear: https://github.com/ACCESS-NRI/um2nc-standalone/blob/ab7b131333300854f0c37a3320026b0b53c6d15a/umpost/um2netcdf.py#L407-L419

An initial experiment cleaning up cube filtering and masking logic is here:
https://github.com/ACCESS-NRI/um2nc-standalone/blob/40/refactor-masking-filtering/umpost/um2netcdf.py

This needs more work to compress some bool checks & warnings. Consider filtering in the existing logic checking function?

**Comment by blimlim** [comment]
This sounds like a good idea to try and simplify/clean up the logic here. I agree that it's currently confusing. 

> Consider filtering in the existing logic checking function?

I like this idea if it's possible, as it seems like the filtering and logic checking perform a lot of similar logic. 

> An initial experiment cleaning up cube filtering and masking logic is here:
https://github.com/ACCESS-NRI/um2nc-standalone/blob/40/refactor-masking-filtering/umpost/um2netcdf.py

Something small I just  noticed in the experimental version: I think the `filtered_cubes` function is filtering out cubes when the mask is missing regardless of the value of `do_mask`.
