### ISSUE TITLE
Extract cube units code from `process()`

### ISSUE THREAD

**Issue by truth-quark** [ACCESS-NRI/um2nc-standalone#54]
The `process()` function contains a code block for fixing units in cubes. This should be extracted and tested as part of #14.

* [x] Refactor this block to a function
* [x] Add unit tests
* [x] Reformat comment block
* [x] Use fstrings
* [x] Use warning mechanism
* [x] Refactor func sig to take _umvar unit_ as a single arg
* [x] use `item_code` over `stash_code`?

**Comment by truth-quark** [comment]
Ooops, accidentally pushed these changes to `develop` without a PR.

**Comment by truth-quark** [comment]
@blimlim & @jo-basevi   would you mind a quick skim over the changes in these accidentally pushed commits?
* https://github.com/ACCESS-NRI/um2nc-standalone/commit/b5424c4c2bff08f6f2c1c5b6b8f1f1bca8ccb991
* https://github.com/ACCESS-NRI/um2nc-standalone/commit/1c86df606ca01eec677781dd2f99c10b26b07268

**Comment by blimlim** [comment]
Changes look good!

**Comment by truth-quark** [comment]
> Changes look good!

Thanks! I'll close this off given the I circumvented the PR mechanism. Ooops...
