### ISSUE TITLE
Refactor `fix_latlon_coord()` function

### ISSUE THREAD

**Issue by truth-quark** [ACCESS-NRI/um2nc-standalone#55]
The `fix_latlon_coord()` function can be cleaned in line with the rest of the `un2nc-standalone` refactor.

Tasks:
* [ ] Move func lower/into call order in the module
* [x] Consider splitting to 2 funcs for `fix_latlon_coord_bounds` & `fix_latlon_coord_var_name`
* [x] Add unittests
* [x] Add docstring
* [x] Add constants for repeated strings
* [x] Bounds arrays should be constants
* [x] `_add_coord_bounds()` should drop leading `_`, it's a nested function, inaccessible as an "implementation detail"
* [x] Clean logic to reduce bounds checks
* [x] Fix up exception handling
  * [x] Move `try/except` from `process()` into `fix_latlon_coord()` (simplifies `process()` for readability)
  * [x] Replace `Exception` class with something more specific
  * [x] Update run script to handle alternate exception class?
* [x] Do the cube coords for lat/lon need to be looked up several times???
* [x] Convert if check calcs to plain functions (for readability & testing)
  * [x] Replace grid strings with existing constants
  * [x] Use descriptive var for values like `lon.points[0]`

**Comment by truth-quark** [comment]
@blimlim this issue should be good if you want to try working on the `um2netcdf` module.

**Comment by blimlim** [comment]
Sounds good! I've started working on this in [this branch](https://github.com/ACCESS-NRI/um2nc-standalone/tree/55/refactor-fix_latlon_coord)

**Comment by truth-quark** [comment]
I think this issue relates to #2, which suggests unit tests are required to verify coordinate rounding. I've added this as another check box item.

**Comment by truth-quark** [comment]
> ~I think this issue relates to #2, which suggests unit tests are required to verify coordinate rounding. I've added this as another check box item.~

Update: this issue doesn't relate to the coordinate rounding.

**Comment by blimlim** [comment]
> * [ ]  Capture real data for unit testing

Just wanted to check, would this mean loading in cubes from model output for the tests? I'm halfway through making an extension of the `DummyCube` class for some of the tests I've been putting together, e.g.

```python
class DummyCubeWithCoords(DummyCube):
     # Dummy cube with coordinates, which can be filled with 
     # DummyCoordinate objects for testing.
     def __init__(self, item_code, var_name=None, attributes=None, units=None, coords = {}):
        super().__init__(item_code, var_name, attributes, units)
        self.coordinate_dict = coords 

     def coord(self, coordinate_name):
        return self.coordinate_dict[coordinate_name]
```

so that would be simplified if we were to use model output. One thing to note with that though: I think it can be quite hard to come across real output on the "river grid", as ESM1.5 currently doesn't output any. Likewise for getting data with the `ENDGAME` grid, I think we'd need to find some output from CM2 rather than ESM1.5. This one is probably possible, but might require getting someone else to run the model for us, as I think the default CM2 configuration converts then deletes the fields files.

**Comment by truth-quark** [comment]
> > * [ ]   Capture real data for unit testing

Ooops, that was a leftover element for testing #2. I've removed the task from this issue.


> Just wanted to check, would this mean loading in cubes from model output for the tests? I'm halfway through making an extension of the `DummyCube` class for some of the tests I've been putting together, e.g.
> 
> ```python
>class DummyCubeWithCoords(DummyCube):
>   # snip the code
> ```
> 
> so that would be simplified if we were to use model output.

On a tangent, the extended `DummyCubeWithCoords` is probably required for testing ~6 other blocks of code, so it's likely to be a very useful contribution. We can discuss these, make a plan & add some issues to make the most use of your work.

**Comment by blimlim** [comment]
> [ ] Do the cube coords for lat/lon need to be looked up several times???

As far as I can tell, the double look ups are unnecessary:
```
cubes = iris.load(ff_file)
>>> cube = cubes[0]
>>> lat = cube.coord("latitude")
>>> lat.points.dtype
dtype('float32')
>>> lat.points = lat.points.astype(np.float64)
>>> lat.has_bounds()
False
>>> lat.guess_bounds()
>>> lat.has_bounds()
True
>>> lat == cube.coord("latitude")
True
```

**Comment by truth-quark** [comment]
@blimlim do you want to tick off the task list items in this issue & close it?

**Comment by blimlim** [comment]
The one point I didn't address in the PR was 
> Move func lower/into call order in the module.

I've added a general item for this in #27 (arrange sub functions into sensible order) and so will close this one!
