### ISSUE TITLE
Feature Requirement: fixing pressure coordinates

### ISSUE THREAD

**Issue by truth-quark** [ACCESS-NRI/um2nc-standalone#6]
From https://github.com/ACCESS-NRI/access-esm1.5-configs/issues/3:

`TODO:` what is the requirement here?
`TODO:` what section of code does this correspond to?

**Comment by MartinDix** [comment]
I think this is a duplicate of #2

**Comment by truth-quark** [comment]
Closing as a duplicate of #2.
