### ISSUE TITLE
Need main functions or similar for entry points in conda

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/um2nc-standalone#81]
The conda deployment supports creating nice [entry points](https://packaging.python.org/en/latest/specifications/pyproject-toml/#entry-points), e.g. the ability to just call `um2nc` from the command line. For this to work e'll need main or similar functions defined, as entry points need to point at a function.

See this related PR where entry points were removed because there were no suitable functions:

https://github.com/ACCESS-NRI/um2nc-standalone/pull/74#issuecomment-2297854954

I started using the pattern shown below as a pretty standard approach in case it's useful

https://github.com/ACCESS-NRI/ncigrafana/blob/master/ncigrafana/parse_lquota.py#L146-L174

The corresponding entry point definition is

https://github.com/ACCESS-NRI/ncigrafana/blob/master/setup.cfg#L34

The point of this approach was to allow for the argument parsing to be tested independently of the call to `main`, and also allows for testing `main` directly in `pytest`, without the need for an entrypoint script (though I don't believe I actually had those tests in this case ... )

**Comment by aidanheerdegen** [comment]
@blimlim if you want/need a post-processing script to be accessible as a command you should specify the requirements in this issue.

**Comment by blimlim** [comment]
It would be great to have the post-processing script available as a command. Specifically we'd want an entry point to the `__main__` block in `conversion_driver_esm1p5.py`

https://github.com/ACCESS-NRI/um2nc-standalone/blob/8aa708d4dbeaa950301173475149a4f37c11ed4a/umpost/conversion_driver_esm1p5.py#L298-L328

Which hopefully should be pretty straightforward to adapt with the pattern in your example. Should I add a PR doing this?

**Comment by aidanheerdegen** [comment]
Yep! Thanks.
